App Layout
MaymoonaAlBoloshi/countrify pull request #7
Opened 2024-10-07 05:19 UTC by ireemalqarni

Closes #6

Description 
- Add a layout to the application

Change log
- New folder added named Layout
- New Component added named Header.jsx

Proof of success
![Scr1](https://github.com/user-attachments/assets/565af71d-919e-489a-9570-83ef324618da)

How to test
- npm run  dev

2024-10-07 06:19 UTC, MaymoonaAlBoloshi requested changes
Please rebase your code to the main/master branch

2024-10-07 06:47 UTC, MaymoonaAlBoloshi requested changes

2024-10-07 06:47 UTC, MaymoonaAlBoloshi commented on src/App.tsx
> +import Header from './layout/Header.jsx';
```suggestion
import Header from './layout/Header';
```
remove the extension of the file on imports, also for the line bellow this

2024-10-07 06:47 UTC, MaymoonaAlBoloshi commented on src/App.tsx
> +      <Header/>
import header in the main layout, and import main layout here

2024-10-07 06:47 UTC, MaymoonaAlBoloshi commented on src/layout/MainLayout.tsx
Complete the layout component

2024-10-10 05:30 UTC, ireemalqarni commented
Closes #8  and #9 

-Description
Add a new file to the application

-Change log
New Component added named Card.jsx contains a list of countries shows in a card with 2 features ( filter & search)

-Proof of success

https://github.com/user-attachments/assets/a942bde5-5083-4696-a09d-296d2ffde5bc




- How to test
npm run dev

2024-10-10 07:19 UTC, MaymoonaAlBoloshi requested changes
looking good but here are some things to update
- Seperate card component as in the issue description
- make sure when we search a single country the cards look decent
- make sure that the filter and search stay on place if we search, right now if you search for a country they move down
- country card should match the design
![image](https://github.com/user-attachments/assets/9b610b92-b176-4dcc-9b81-e74695aaccfc)
- filter and search inputs should match the design
![image](https://github.com/user-attachments/assets/598d1c74-6991-4c02-8794-4d76fe992ea0)
- make sure overall spacing is close enough

2024-10-13 12:55 UTC, MaymoonaAlBoloshi approved these changes
🔥 🚀  great job

2024-10-13 12:56 UTC, merged